const DOCUMENT = 'createWorkout/';

export const SET_WORKOUT_TEMPLATE_NAME = DOCUMENT + 'SET_WORKOUT_TEMPLATE_NAME';
export const ADD_EXERCISE_TEMPLATE = DOCUMENT + 'ADD_EXERCISE_TEMPLATE';
export const CREATE_WORKOUT_TEMPLATE = DOCUMENT + 'CREATE_WORKOUT_TEMPLATE';
export const CREATE_WORKOUT_TEMPLATE_SUCCESS =
  DOCUMENT + 'CREATE_WORKOUT_TEMPLATE_SUCCESS';
export const CREATE_WORKOUT_TEMPLATE_ERROR =
  DOCUMENT + 'CREATE_WORKOUT_TEMPLATE_ERROR';
