const DOCUMENT = 'sets/';

export const CREATE_NEW_SET = DOCUMENT + 'CREATE_NEW_SET';
export const CREATE_NEW_SET_SUCCESS = DOCUMENT + 'CREATE_NEW_SET_SUCCESS';
export const CREATE_NEW_SET_ERROR = DOCUMENT + 'CREATE_NEW_SET_ERROR';
