const DOCUMENT = 'template/';

export const SET_WORKOUT_TEMPLATE_NAME = DOCUMENT + 'SET_WORKOUT_TEMPLATE_NAME';
export const ADD_EXERCISE_TEMPLATE = DOCUMENT + 'ADD_EXERCISE_TEMPLATE';
export const CREATE_WORKOUT_TEMPLATE = DOCUMENT + 'CREATE_WORKOUT_TEMPLATE';
export const CREATE_WORKOUT_TEMPLATE_SUCCESS =
  DOCUMENT + 'CREATE_WORKOUT_TEMPLATE_SUCCESS';
export const CREATE_WORKOUT_TEMPLATE_ERROR =
  DOCUMENT + 'CREATE_WORKOUT_TEMPLATE_ERROR';
export const GET_WORKOUT_TEMPLATES = DOCUMENT + 'GET_WORKOUT_TEMPLATES';
export const GET_WORKOUT_TEMPLATES_SUCCESS =
  DOCUMENT + 'GET_WORKOUT_TEMPLATES_SUCCESS';
export const GET_WORKOUT_TEMPLATES_ERROR =
  DOCUMENT + 'GET_WORKOUT_TEMPLATES_ERROR';
export const GET_EXERCISE_TEMPLATES = DOCUMENT + 'GET_EXERCISE_TEMPLATES';
export const GET_EXERCISE_TEMPLATES_SUCCESS =
  DOCUMENT + 'GET_EXERCISE_TEMPLATES_SUCCESS';
export const GET_EXERCISE_TEMPLATES_ERROR =
  DOCUMENT + 'GET_EXERCISE_TEMPLATES_ERROR';
