const DOCUMENT = 'workout/';

export const START_WORKOUT = DOCUMENT + 'START_WORKOUT';
export const START_WORKOUT_SUCCESS = DOCUMENT + 'START_WORKOUT_SUCCESS';
export const START_WORKOUT_ERROR = DOCUMENT + 'START_WORKOUT_ERROR';
export const START_NEW_SET = DOCUMENT + 'START_NEW_SET';
export const START_NEW_SET_SUCCESS = DOCUMENT + 'START_NEW_SET_SUCCESS';
export const START_NEW_SET_ERROR = DOCUMENT + 'START_NEW_SET_ERROR';
export const START_NEW_EXERCISE = DOCUMENT + 'START_NEW_EXERCISE';
export const START_NEW_EXERCISE_SUCCESS =
  DOCUMENT + 'START_NEW_EXERCISE_SUCCESS';
export const START_NEW_EXERCISE_ERROR = DOCUMENT + 'START_NEW_EXERCISE_ERROR';
export const GET_ACTIVE_WORKOUT_EXERCISES =
  DOCUMENT + 'GET_ACTIVE_WORKOUT_EXERCISES';
export const GET_ACTIVE_WORKOUT_EXERCISES_SUCCESS =
  DOCUMENT + 'GET_ACTIVE_WORKOUT_EXERCISES_SUCCESS';
export const GET_ACTIVE_WORKOUT_EXERCISES_ERROR =
  DOCUMENT + 'GET_ACTIVE_WORKOUT_EXERCISES_ERROR';
export const END_WORKOUT = DOCUMENT + 'END_WORKOUT';
export const END_WORKOUT_SUCCESS = DOCUMENT + 'END_WORKOUT_SUCCESS';
export const END_WORKOUT_ERROR = DOCUMENT + 'END_WORKOUT_ERROR';
